name: Linty
on:
  pull_request:
    branches:
    - master
jobs:

  linty:
    name: GoLinty
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Go-Linty
      uses: ArangoGutierrez/GoLinty-Action@go-1.12-alpine
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
