#!/bin/sh

# De-linting is a time-consuming process. The aim of LINTY is to support an
# iterative process to clear out lint. It uses a configuration file which lists
# packages that currently contain lint, and ensures that:
#
#  - packages listed in the configuration are removed once they are free of lint
#  - packages not listed in the configuration continue to be free of lint
#
# If either of the above statements is FALSE, LINTY prints out a warning and
# exits. If both statements are TRUE, LINTY prints out a table of lint counts
# for the packages that are listed in its configuration.
set -e
set -o pipefail

if [[ -z "$GITHUB_TOKEN" ]]; then
	echo "Set the GITHUB_TOKEN env variable."
	exit 1
fi

if [[ -z "$GITHUB_REPOSITORY" ]]; then
	echo "Set the GITHUB_REPOSITORY env variable."
	exit 1
fi

# Small hack to sanitize GOPATH
WORKDIR="/go/src/github.com/${GITHUB_REPOSITORY}"
# create go work dir
mkdir -p ${WORKDIR}
# copy all files from workspace to work dir
cp -R /github/workspace/* ${WORKDIR}
cp -R /github/workspace/.linty ${WORKDIR}
# cd into the work dir and run all commands from there
cd ${WORKDIR}

if [[ ! -f ".linty/linty.conf" ]]; then
	echo "No linty conf file found"
	exit 1
fi

URI=https://api.github.com
API_VERSION=v3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json;application/vnd.github.antiope-preview+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"


linty(){
for pkg in `go list ./...`; do
	# Check package for lint
	lint=$(golint -set_exit_status ${pkg} 2>/dev/null)
	has_lint=$?

	# Check if the package is expected to have lint
	if grep -Fxq $pkg ".linty/linty.conf"; then
		if [ "$has_lint" -eq 1 ]; then
			# Still has lint...
			lint_count=$(echo "$lint" | wc -l)
			printf " %5s | %s\n" "$lint_count" "$pkg" >> "$1"
		else
			# Lint free!
			echo -e  "WARNING: package $pkg contains NO lint, but is listed in the LINTY config.\n"
			echo -e  "Please remove it from 'linty.config'!\n"
			rm $1
			exit 0
		fi
	else
		if [ "$has_lint" -eq 1 ]; then
			# New lint...
			echo -e  "$lint\n\n"
			echo -e  "ERROR: package $pkg contains NEW lint. Please address the issues listed above!\n"
			rm $1
			exit 0
		fi
	fi
done

# Sort results by count
sort -nr $1 -o $1

# Print results table
echo -e "##  L I N T Y   W A L L   O F   S H A M E "
echo -e " Count | Name of Linty Package\n"
while IFS= read -r var
	do
		echo -e  "$var\n"
	done < "$1"
echo -e "\\n"
echo -e "Help LINTY fight the good fight, golint today!\n"
}

main(){
	action=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
	ref=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
	REPO_OWNER=$(jq --raw-output .pull_request.head.repo.owner.login "$GITHUB_EVENT_PATH")
	REPO_NAME=$(jq --raw-output .pull_request.head.repo.name "$GITHUB_EVENT_PATH")
	ISSUE_NO=$(jq --raw-output .number "$GITHUB_EVENT_PATH")

# Temporary table file
tmp_file="/tmp/linty.${ref}"
touch $tmp_file
if [[ ! -f "/tmp/linty.${ref}" ]]; then
	echo "Failed to create /tmp/linty.${ref}"
	exit 1
fi

linty_out=$(linty $tmp_file)
JSON_STRING=$( jq -n \
				--arg bd "$linty_out" \
				'{body: $bd}' )

echo ""
echo "${JSON_STRING}"
echo ""

# the real action!
curl -sSL -H "${AUTH_HEADER}" -H "${API_HEADER}" \
 -H "Content-Type: application/json" \
 -X POST -d "${JSON_STRING}" \
 "${URI}/repos/${REPO_OWNER}/${REPO_NAME}/issues/${ISSUE_NO}/comments"

# Remove temporary file
if [[ -f "$tmp_file" ]]; then
	rm $tmp_file
fi
}

main "$@"
